### ISSUE TITLE
require broken in early Node.js 13.x runtime

### ISSUE THREAD

**Issue by panva** [WebReflection/html-escaper#1]
See below, 2.0.1 is not usable on these Node versions, since its a dependency for CI code coverage tools such as [`istanbul`](https://github.com/istanbuljs/istanbuljs/issues/550) we're seeing failures in our CI that tests specific node release lines that changed V8 versions because of this.

```
node -v
v13.0.0

node -e "require('html-escaper')"                               
internal/modules/cjs/loader.js:417
      throw e;
      ^

Error: Package exports for '/Users/panva/repo/ultimate-jose/node_modules/html-escaper' do not define a '.' subpath
    at resolveExports (internal/modules/cjs/loader.js:414:17)
    at Function.Module._findPath (internal/modules/cjs/loader.js:487:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:782:27)
    at Function.Module._load (internal/modules/cjs/loader.js:688:27)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:116:20)
    at Object.runInThisContext (vm.js:306:38)
    at Object.<anonymous> ([eval]-wrapper:9:26) {
  code: 'MODULE_NOT_FOUND'
}
```

dtto on 13.0.1 and 13.1.0, later versions are okay.

**Comment by WebReflection** [comment]
I am using this in node 13.11 ... what's going on?

**Comment by WebReflection** [comment]
also, why would istanbul, which is deprecated, bring in a major version bump?

**Comment by panva** [comment]
13.0.0, 13.0.1 and 13.1.0 are affected. And you released a patch release, not a major one.

<img width="654" alt="Screenshot 2020-03-27 14 05 30" src="https://user-images.githubusercontent.com/241506/77758898-16b82a80-7034-11ea-894f-a91a3b1e5656.png">

Instabul is the repo, containing `nyc` and shared `istanbul-reports` libs.

**Comment by WebReflection** [comment]
OK, I've thought it was because of the dualmodule ... then I don't understand what's going on here ... this is valid CommonJS, right? https://github.com/WebReflection/html-escaper/blob/master/cjs/index.js

**Comment by WebReflection** [comment]
To clarify, the **v2** is all about having a dual module. It works down to node 10 for me, I have no idea what is this issue about. Can you `node -e "require('html-escaper/cjs')"` instead, or use version 1, as literally nothing changed in this module, if not for the dual module structure?

**Comment by panva** [comment]
Whatever changed in v2.0.1 broke `require('html-escaper')` in those three mentioned node versions, as a result, through the matching semver of ^2.0.0 `nyc`, `c8` and other tools can no longer produce html reports on those node versions.

**Comment by coreyfarrell** [comment]
@WebReflection I think the issue is that node.js 13.0.0 - 13.1.0 had a bug in the `exports` processing.  My understanding is that this can be worked around by using array notation to provide the "default" export:
```js
"exports": [
  {"import": "./esm/index.js"},
  "./cjs/index.js"
]
```

I will `nvm install 13.0.0` and manually patch the installed `node_modules/html-escaper/package.json` to confirm this.

**Comment by WebReflection** [comment]
> Whatever changed in v2.0.1 broke require('html-escaper') in those three mentioned node versions

v2 amended changes meant for 2 ... which is about dual modules.

As the issue is with node, not with my code, would you be OK with a patch that rollback those dual module related changes, followed by a minor bump to actually fix that again, since that's how dual modules work from now on?

**Comment by WebReflection** [comment]
@panva this is fixed now ... can you confirm if I go _minor_ everything should be OK? otherwise I'll go major **again** because I use already this module as ESM and current state is not ideal at all.

**Comment by panva** [comment]
Minor won't do it, `istanbul-reports` requires `^2.0.0`.

**Comment by coreyfarrell** [comment]
@WebReflection the following `exports` is compatible with 13.0.0+:
```js
  "exports": {
    ".": [
      {
        "import": "./esm/index.js"
      },
      "./cjs/index.js"
    ]
  },
```

If you plan to re-release 2.0.1 as 2.1.0 this would break istanbul-reports again.  If you don't want to use the above `exports` format I could do a new release of istanbul-reports to lock html-escaper to a specific version.

**Comment by WebReflection** [comment]
@coreyfarrell I've already fixed the issue, right? I am going major next, as I don't want deprecated package syntax due broken node loaders, but thanks for the hint, and let me know if you have any other issue.

**Comment by WebReflection** [comment]
@panva @coreyfarrell **V3** is out, apologies for the bumpy ride in _V2_ 👋

**Comment by coreyfarrell** [comment]
@WebReflection yes you've fixed the issue and if you are doing a major bump to reintroduce the dual mode that will resolve the issue so you shouldn't get anymore complaints for nyc / c8 / jest users.

For the record the array notation of the exports field is not deprecated and I know removal/deprecation of support for the array structure would be aggressively opposed by members of the nodejs modules team.  That said I agree the array notation is ugly so I completely understand not wanting to use it.

**Comment by panva** [comment]
@WebReflection thank you!

**Comment by WebReflection** [comment]
@coreyfarrell thanks for expanding on that, yet I think trusting a non LTS version of node with a broken loader will backfire sooner or later, but it was me messing up with v2, and now v3 explicitly targets ESM only and hopefully I won't ever need to touch ever again this module 🎉
