### ISSUE TITLE
Add null/undefined check

### ISSUE THREAD

**Issue by binarykitchen** [WebReflection/html-escaper#3]
To avoid this error

```
TypeError: String.prototype.replace called on null or undefined
```

Thanks

**Comment by WebReflection** [comment]
would you rather prefer `null` or `undefined` as resulting string instead? I personally don't, but also this API is simple: string in, escaped string out, it's working well for 43M downloads per months, not sure that should change 🤔

**Comment by binarykitchen** [comment]
I read you but 43M downloads isn't a valid argument I think. Because there are plenty of bots, dependencies or lazy programmers but I'm the first making a move to raise this :)

Anyway, imagine this scenario:

1. In some API response we have these fields
```
[
  { name: 'banana', desc: 'yummy from brazil', price: 3 },
  { name: 'apple', price: 6 },
  { name: 'plum', price: 8 }
]
```
where one doesn't have the description.

2. Then imagine a React table component with the render fn like this:
```js
return (
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Fruit</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      {rows.map((row, i) => {
        return (
          <tr>
            {row.cells.map((cell) => {
              return <td>{escape(cell.value)}</td>
            })}
          </tr>
        )
      })}
    </tbody>
  </table>
)
```

If it's the cell for the description of the apple, it will crash cos undefined in API response.

Just a simplification. I could add a null check like

```js
{cell.value && escape(cell.value)}
```

but that feels silly if I'd have to do this everywhere throughout the whole app. And secondly you cannot trust API responses. Secondly it's okay if not everything has a description.

Hope this makes sense?

**Comment by WebReflection** [comment]
sort of ... basically you are saying your server side / end point has an inconsistent, non homogeneous results, you pass random properties you don't know these exist, and you expect this module to fix, exactly, what?

falsy values, excluding `null` and `undefined`, are also stringified, so using `escape(thing || '')` is not an option, so once again, what do you expect from this API by passing `null` or `undefined`?

discarding falsy values would be a breaking change, that is the 43M downloads arguments, I can't just naively change the way this module behaves, but I'm curious to know what are your expectations here, and here few hints:

 * for such widely used module, having an extra check for `null` or `undefined` *might* be a sensible performance impact
 * people having errors so far fixed *their* data issue, instead of expecting this module to "*behave like jQuery*"
 * if the value is actually *null* or *undefined*, what do you expect to happen? empty string is a valid answer, and the fact it's been throwing to date helps making this change possible, but can you see why I'm not so sure this should change at all?

**Comment by coreyfarrell** [comment]
If html-escaper were to handle `null` / `undefined` I think it could just stringify the argument, for example:
```js
export const escape = es => replace.call(`${es}`, ca, pe);
// ...
export const unescape = un => replace.call(`${un}`, es, cape);
```

This would cause `escape() === 'undefined' && escape(null) === 'null'`.  Stringifying nullish values would be consistent with what already happens to other non-string types.

**Comment by binarykitchen** [comment]
yeah it would be a breaking change, agree. and that's okay if mentioned in changelog.

i think if `undefined` then i would return `undefined` again so that anything else further up in the code chain will notice it. because undefined means void, unknown, nothing to process further.

how about

```js
export const escape = es => {
  if (es === null || es === undefined) return es
  replace.call(`${es}`, ca, pe);
}
```

i reckon this is a classic question many other maintainers have discussed before. maybe do some research how some well-known libraries handle this scenario?

**Comment by WebReflection** [comment]
> If html-escaper were to handle null / undefined I think it could just stringify the argument

a `symbol` would fail there thought, so if this is about fixing users mistakes, in terms of passed data, I rather fix all cases, meaning `String(input)`

> i think if undefined then i would return undefined again 

that's not what escaping APIs do though, but also you already disagree with Corey expectations, and the rest of the APIs:

```js
escape(null); // "null"
escape(undefined); // "undefined"

encodeURIComponent(null); // "null"
encodeURIComponent(void 0); // "undefined"
```

so, once again, should it be on this module to fix unexpected input, or maybe developers could be a bit more aware of the data they pass to an utility which purpose is to *escape strings* ?

'cause for symmetry, there could be a counter argument that `unescape` should also fix unexpected data ... I still prefer the current behavior though

**Comment by loucyx** [comment]
One easy solution for devs running into this is to just do a small wrapper:
```typescript
/**
 * Escapes given `value` if is of type string, or returns an empty string.
 * @param {string|null} [value] Value to parse.
 * @returns {string} Parsed string or empty string.
 */
const safeEscape = value => typeof value === "string" ? escape(value) : "";
```
Or if you want to reuse the logic, something like:
```typescript
/**
 * Checks if the value is string before running given function, or returns an empty string.
 * @param {(value: string)=>string} [fn] Function to wrap
 * @returns Curried function with `fn` in closure.
 */
const safeWrapper = fn =>
  /**
   * @param {string|null} [value] Value to parse.
   * @returns {string} Parsed string or empty string.
   */
  value => typeof value === "string" ? fn(value) : "";

const safeEscape = safeWrapper(escape);
```
And then your code would look like this:
```jsx
rows.map(({ cells }) => (
  <tr>
    {cells.map(({ value }) => (
      <td>{safeEscape(value)}</td>
    )}
  </tr>
));
```
Or you can skip all the previous steps and just:
```jsx
rows.map(({ cells }) => (
  <tr>
    {cells.map(({ value = "" }) => (
      <td>{escape(value)}</td>
    )}
  </tr>
));

// or

rows.map(({ cells }) => (
  <tr>
    {cells.map(({ value }) => (
      <td>{escape(value ?? "")}</td>
    )}
  </tr>
));
```

**Comment by WebReflection** [comment]
@lukeshiru thanks, it's indeed trivial to wrap this module and make it sloppy ... but also there is an important thing to consider:

```js
unescape(escape(null))
```

if `escape` doesn't throw on `null` or `void 0`, then it propagates that value to `unescape` that should also handle the case, or the two i/o utilities become asymmetric, which is undesired.

This [poll](https://twitter.com/WebReflection/status/1362284871209660419) is also showing divergent opinions here, and the more I think about this issue, the more I think this module *should* throw if the input cannot be represented as string, while having `null` or `undefined` in production, as string content, is *always* undesired, even if it'll make the API consistent with other primitives that can borrow the `replace` from the `String.prototype`.

So far, I believe adding a proper *TS* signature, via *JSDoc*, is the best thing I can do, and wrapping this module, or creating a module based on this one that does *any* desired thing, might be the solution to all cases, without me needing to bump major version for something I'm not even convinced is a good idea.

**Comment by WebReflection** [comment]
Actually, I do like this approach. The language provides a way to deal with unknown data, and as changes to this module will be more awkward than beneficial, for something easy to handle *when* it's needed, I think I'll close this as *won't fix*.

```js
rows.map(({ cells }) => (
  <tr>
    {cells.map(({ value }) => (
      <td>{escape(value ?? "")}</td>
    )}
  </tr>
));
```

A new `html-null-escaper` module could be the wrapper that does this:

```js
import {escape as safeEs, unescape as safeUn} from 'html-escaper';

export const escape = input => input == null ? input : safeEs(input);
export const unescape = input => input == null ? input : safeUn(input);
```

This allows propagating both `null` and `undefined` without changing anything else, and performance should be *almost* at pair.

It will still throw on unexpected input such as `symbol` though, which is another thing I don't want to fix in here, as symbols should never pass through this API, so "*fail fast*" is what should happen.

**Comment by WebReflection** [comment]
@binarykitchen I have created [html-sloppy-escaper](https://www.npmjs.com/package/html-sloppy-escaper) which should put an end to this discussion by providing an *API* that is identical, it's based on this very same module, but it *never* throws errors, and it returns `null` or `undefined` when either is passed along, for both `escape` and `undescape`.

I hope this satisfies your requirements 👋

**Comment by binarykitchen** [comment]
Hmmm the symmetry argument sold me here plus didn't know the output of `encodeURIComponent(null)` is `"null"`.

Don't have to make a html-sloppy-escaper for me, I can shim it myself with your above changes :)

Thanks for the discussion anyway guys.

**Comment by WebReflection** [comment]
Well, it wasn’t strictly *for you*, ‘cause I’m sure somebody else might want a module that never throws, so it’s there, tested, covered, and done 👋

**Comment by WebReflection** [comment]
P.S. also worth mentioning that to create a module takes 1 minute: `npx modulestrap ...` done 😉
