### ISSUE TITLE
&nbsp; is not (un)escaped

### ISSUE THREAD

**Issue by henricook** [WebReflection/html-escaper#4]
I may be able to fix  this myself, creating an issue for posterity.

`&nbsp;` is not covered by current escaping+unescaping practices.

**Comment by WebReflection** [comment]
that's expected ... this module (please read how many projects are using it already, we're 43 millions downloads per months) just escapes undesired chars, same way PHP or any other PL does. HTML has `&copy;` too and many others, yet none of these are problematic in terms of content. There is a specification around escaping safe HTML, and spaces are not part of it, hence I'm afraid this is *not* where anything should change/be fixed, as this module does what specs mention: escape `<`, `>`, `&`, `'`, and `"`, 'cause these are always problematic in the layout, or as attribute content (while `&nbsp;` has an `&` and if you want to show exactly that, this module rightly produces `&amp;nbsp;`, as that's what you'd expect from this module).

**Comment by henricook** [comment]
Thanks @WebReflection !

**Comment by WebReflection** [comment]
if helping, this module is the equivalent of [htmlspecialchars](https://www.php.net/manual/en/function.htmlspecialchars.php)

**Comment by WebReflection** [comment]
P.S. maybe the comparison with PHP function should be mentioned in the readme, so this was a good call for clarification
