### ISSUE TITLE
🐛 Unescape is not working properly

### ISSUE THREAD

**Issue by ghost** [WebReflection/html-escaper#5]
<ol section_id="one">
  <li section_id="one">
    This is section 3 &lt;strong&gt;Oyee&lt;/strong&gt; But not okay
  </li>
  <li section_id="one">yes not sure</li>
</ol>

strong is not unescaped

Thr original string is 
<h1 name="slate-heading" section_id="one">Hello</h1><h2 section_id="one">Okay this is me. &lt;div name=&quot;age&quot; style=&quot;display:inline;background:#DBF6F8;font-size:1rem;height:1rem;padding:0.5rem;gap:0.5rem;align-items:center&quot;&gt;&lt;span style=&quot;margin:0 0.5rem&quot;&gt;10&lt;/span&gt;&lt;span style=&quot;margin:0 0.5rem&quot;&gt;age&lt;/span&gt;&lt;/div&gt;</h2><h1 name="slate-heading" section_id="one">Section 2</h1><ol section_id="one">&lt;li section_id=&quot;one&quot;&gt;This is section 3  &amp;lt;strong&amp;gt;Oyee&amp;lt;/strong&amp;gt; But not okay  &lt;/li&gt;&lt;li section_id=&quot;one&quot;&gt;yes not sure&lt;/li&gt;</ol>

**Comment by WebReflection** [comment]
can you use a code example instead as I have no idea what you are doing? also please consider this module has 73 million monthly downloads and 343 dependents projects, beside being 100% code covered, so that it's very likely that *you* are doing something wrong ...

**Comment by ghost** [comment]
Sorry, I was escaping multiple times in the code. After modifying code it is working as expected
