### ISSUE TITLE
question: What is the benefit of storing the String.prototype.replace in a const?

### ISSUE THREAD

**Issue by asonnleitner** [WebReflection/html-escaper#6]
Hello, 
I am just curious, what is the benefit of storing the `replace` in a const instead of calling it directly on the string.
I've seen this already a few times but not sure why some do that.

Thanks

**Comment by WebReflection** [comment]
Teo reasons:
 1. No library changing, intercepting, or polluting the native method would make this module fail at runtime
 2. The input is not necessarily a string, so it’s not necessarily exposing a replace method. You can pass null, undefined, an array, or an object, to this API and see it not throwing errors ever 👍
